### ISSUE TITLE
No IP in <static mapping>, error.

### ISSUE THREAD

**Issue by baudneo** [EasyG0ing1/Migration#3]
Tried running the binary but I get this error that tells me to review the XML file for empty static mappings.

I reviewed the file and couldn't not see any empty staticmappings. Just wondering if you can add a blurb to the logs for which line or which interface the config error is on?

Thanks for your work!

**Comment by baudneo** [comment]
Found the issue, The staticmapping had <cid> rather than <ipaddr>.

**Comment by EasyG0ing1** [comment]
@baudneo I updated the tool so that it recognizes when there is only a CID and no MAC address. It doesn't, of course include those mappings in the new config, but when its done creating the new config, it will give you a list of all mappings that only had a CID so you can either add them manually or go back and add a mac address then re-start the migration process.
